# Generated by Django 3.2.4 on 2021-06-22 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('Correo', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Correo')),
                ('Nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('Contraseña', models.CharField(max_length=30, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('Correo', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Correo')),
                ('Nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('Categoria', models.CharField(max_length=15, verbose_name='Categoria')),
                ('Detalles', models.CharField(max_length=150, verbose_name='Detalles')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuenta')),
            ],
        ),
    ]
